// Generated by CoffeeScript 1.12.7
(function() {
  module.exports.ShopAPI = require("./shop_api");

  module.exports.SiteAPI = require("./site_api");

  module.exports.ShopAndSiteAPI = require("./shop_and_site_api");

}).call(this);
